[colors.bright]
black = "#4C566A"
blue = "#82c0ff"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#d00000"
white = "#f5f5f5"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#82c0ff"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#d00000"
white = "#f5f5f5"
yellow = "#EBCB8B"

[colors.primary]
background = "#18191a"
foreground = "#f5f5f5"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.normal]
family = "Consolas"

[schemes.Basic.primary]
background = "#18191A"
foreground = "#E0E0E0"

[schemes.Nord.bright]
black = "#4C566A"
blue = "#82c0ff"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#d00000"
white = "#f5f5f5"
yellow = "#EBCB8B"

[schemes.Nord.normal]
black = "#3B4252"
blue = "#82c0ff"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#d00000"
white = "#f5f5f5"
yellow = "#EBCB8B"

[schemes.Nord.primary]
background = "#18191a"
foreground = "#f5f5f5"

[scrolling]
history = 100000

[window]
decorations = "none"
dynamic-title = false
startup_mode = "Maximized"
