#!/bin/bash

NVIM=$(which nvim)

_install_appimages() {
    pushd $HOME
    [ ! -d ./Applications ] && mkdir Applications
    cd Applications
    wget https://github.com/neovim/neovim/releases/download/v0.8.3/nvim.appimage -O nvim
    [ -z "${NVIM}" ] && NVIM="~/Applications/nvim"
    chmod +x $NVIM
    popd
}

install() {
    if [ $2 = "deps" ]
    then
        if [ -x "$(command -v pacman)" ]
        then
            sudo pacman -Sy stow neovim curl fd ripgrep fzf git-delta
        elif [ -x "$(command -v apt-get)" ]
        then
            _install_appimages
            sudo apt-get install stow fd-find curl ripgrep fzf python3-pip
        fi
        python3 -m pip install pynvim
        git submodule update
    fi

    pushd ~/
    [ -f .bashrc ] && mv .bashrc .bashrc.old
    cd .dotfiles

    for folder in $(ls -d */ | sed "s/,/ /g")
    do
        stow $folder
    done
    popd
}

remove() {
        pushd ~/.dotfiles
        for folder in $(ls -d */ | sed "s/,/ /g")
        do
            stow -D $folder
        done
        popd
}

reinstall() {
    remove
    install
}

case $1 in
    "install") install $@ ;;
    "remove") remove $@ ;;
    "reinstall") reinstall $@ ;;
esac
